spring:
  kafka:
    bootstrap-servers: localhost:29092
  datasource:
    url: jdbc:postgresql://localhost:5432/movie-streaming
    username: admin
    password: admin

wiremock:
  server:
    port: 9000

imdb:
  api:
    url: http://localhost:${wiremock.server.port:9000}
