apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: video-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-info
  template:
    metadata:
      labels:
        app: movie-info
    spec:
      containers:
        - name: movie-info
          image: localhost:32000/movie-info
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: movie-info-env